### ISSUE TITLE
FILM could not be found in this folder: W:\stable-diffusion-webui\extensions\animator_extension\predict.py

### ISSUE THREAD

**Issue by ShmuelRonen** [Animator-Anon/animator_extension#34] opened 2023-08-26 03:13 UTC
I installed frame-interpolation-film. By itself it works great and creates photos and videos in between.
I also made the film.bat and set it in the settings so that Animator can find it. 
But when I running Animator with FILM Interpolation check it gives this strange error: FILM could not be found in this folder: W:\stable-diffusion-webui\extensions\animator_extension\predict.py

The Film.bat locate in W:\stable-diffusion-webui\extensions\animator_extension

Can this be resolved?

I check in also on vlad-automatic with same error

**Comment by Animator-Anon** [comment] 2023-08-27 00:58
Can you post the error message from the console?

**Comment by ShmuelRonen** [comment] 2023-08-27 01:51
> Can you post the error message from the console?

venv "W:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: v1.6.0-RC-5-gac1abf3d
Commit hash: ac1abf3de68614d575de79347a2aa4a33ee4d6bb

Installing requirements 1 for Infinite-Zoom

Launching Web UI with arguments: --medvram
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: infinite-zoom.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 2, in <module>
        from iz_helpers.ui import on_ui_tabs
      File "W:\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\iz_helpers\ui.py", line 4, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (W:\stable-diffusion-webui\webui.py)

---
Loading weights [0b76532e03] from W:\stable-diffusion-webui\models\Stable-diffusion\crystalClearXL_ccxl.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: W:\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Startup time: 14.2s (prepare environment: 4.6s, import torch: 3.2s, import gradio: 1.1s, setup paths: 0.9s, initialize shared: 0.3s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 1.1s, create ui: 0.8s, gradio launch: 1.3s).
Applying attention optimization: Doggettx... done.
Traceback (most recent call last):
  File "W:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "W:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "W:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "W:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "W:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "W:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "W:\stable-diffusion-webui\modules\ui_extra_networks.py", line 392, in pages_html
    return refresh()
  File "W:\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "W:\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "W:\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "W:\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "W:\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 69, in list_items
    for index, name in enumerate(networks.available_networks):
RuntimeError: dictionary changed size during iteration
Model loaded in 7.7s (load weights from disk: 1.5s, create model: 0.6s, apply weights to model: 2.2s, calculate empty prompt: 3.2s).
Script Path (myprocess):  W:\stable-diffusion-webui
FILM could not be found in this folder: W:\stable-diffusion-webui\extensions\animator_extension\predict.py
Error: Failed to apply styles to templates: argument of type 'NoneType' is not iterable
Initial Image: None
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.63it/s]
==========================================================================================00 [00:11<29:35,  1.68it/s]
A tensor with all NaNs was produced in VAE.
Web UI will now convert VAE into 32-bit float and retry.
To disable this behavior, disable the 'Automatically revert VAE to 32-bit floats' setting.
To always start with 32-bit VAE, use --no-half-vae commandline flag.
==========================================================================================
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.88it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.89it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.90it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.91it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.89it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.87it/s]
 75%|█████████████████████████████████████████████████████████████▌                    | 6/8 [00:03<00:01,  1.65it/s]
Total progress:   2%|█▌                                                            | 74/3000 [01:37<49:08,  1.01s/it]

**Comment by Animator-Anon** [comment] 2023-08-27 03:05
I removed a redundant check for the predict.py in the FILM folder. It still expects to find the batch file you set in options though. That is expected to do the work of launching the FILM scripts.

**Comment by ShmuelRonen** [comment] 2023-08-27 04:07
Thanks. Now it does not alert error on execute. I Let it work. 
What is the result I should meet as a result of using Film? Continuous and smoother movement? Does Smoothing_Frames affect when Film is active?

**Comment by ShmuelRonen** [comment] 2023-08-27 04:26
This is the result:

https://github.com/Animator-Anon/animator_extension/assets/80190186/a8392fbc-516b-405f-b777-40749c14d87d

**Comment by Animator-Anon** [comment] 2023-08-27 04:47
Looks like you have a high denoise value? The picture is changing quite a bit frame to frame. It might be hard for FILM to predict the movement..
FILM is going to try and create intermediate frames between every frame you generate. The context doesn't run from one pair of frames to the next.
I would try to generate a longer animation, with a lower framerate, and set the number of intermediate frames to 2 or 3.

**Comment by ShmuelRonen** [comment] 2023-08-27 05:28
The denoise value was = 0.4 and frame rate = 15 
I will try to decrease the frame rate to 2

**Comment by ShmuelRonen** [comment] 2023-08-27 05:45
After set frame rate = 2 I got this error:

Script Path (myprocess):  W:\stable-diffusion-webui
Error: Failed to apply styles to templates: argument of type 'NoneType' is not iterable
Initial Image: None
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.92it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.07it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.06it/s]
Done. progress:  39%|██████████████████████▍                                   | 1163/3000 [1:34:52<25:34,  1.20it/s]

W:\stable-diffusion-webui\extensions\animator_extension>call C:\Users\derec\miniconda3\condabin\conda.bat activate film
C:\Users\derec\miniconda3\envs\film\python.exe: Error while finding module specification for 'eval.interpolator_cli' (ModuleNotFoundError: No module named 'eval')
FILM failed to produce a result.



https://github.com/Animator-Anon/animator_extension/assets/80190186/1ddc896c-cfcc-4412-8e6f-a1e5cc07488e

**Comment by ShmuelRonen** [comment] 2023-08-27 07:24
I installd eval

![eval 1](https://github.com/Animator-Anon/animator_extension/assets/80190186/4665610e-fd3a-49ba-86e5-f7f55e719147)
![eval 2](https://github.com/Animator-Anon/animator_extension/assets/80190186/8814e0b3-d35a-4381-8f27-5415f0b192f4)
now I got this error

100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.03it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.04it/s]
Done. progress:  51%|█████████████████████████████▍                            | 1523/3000 [3:19:56<20:41,  1.19it/s]

W:\stable-diffusion-webui\extensions\animator_extension>call C:\Users\derec\miniconda3\condabin\conda.bat activate film
C:\Users\derec\miniconda3\envs\film\python.exe: Error while finding module specification for 'eval.interpolator_cli' (ModuleNotFoundError: No module named 'eval')
FILM failed to produce a result.

**Comment by Animator-Anon** [comment] 2023-08-27 11:33
Have you tested the bat file by itself? It might be related to virtual environments, sounds like the film script cant find dependencies when run via the bat file.

**Comment by ShmuelRonen** [comment] 2023-08-27 13:54
I try

**Comment by ShmuelRonen** [comment] 2023-08-27 14:25
I addapt the film.bat as stand alone:

@echo off

:: Activate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat activate film

:: Execute the Python script for interpolation
python -m eval.interpolator_cli ^
   --pattern "photos" ^
   --model_path pretrained_models\film_net\Style\saved_model ^
   --times_to_interpolate 6 ^
   --output_video

:: Deactivate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat deactivate

pause


and it works perfect


![1](https://github.com/Animator-Anon/animator_extension/assets/80190186/90118953-342c-4ba4-a76d-a16ec09b961b)
![2](https://github.com/Animator-Anon/animator_extension/assets/80190186/0e90abee-1711-4742-9a6e-d253677dc213)

https://github.com/Animator-Anon/animator_extension/assets/80190186/a59a52c3-552e-48f4-9430-33e313cbb13e

**Comment by ShmuelRonen** [comment] 2023-08-27 15:29
Now I try to enforce film.bat to finde evale path: C:\frame-interpolation\eval

@echo off
pushd C:\frame-interpolation

call %USERPROFILE%\miniconda3\condabin\conda.bat activate film
python -m eval.interpolator_cli --pattern "%1" --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate %2
call %USERPROFILE%\miniconda3\condabin\conda.bat deactivate


then I got new error:

Script Path (myprocess):  W:\stable-diffusion-webui
Error: Failed to apply styles to templates: argument of type 'NoneType' is not iterable
Initial Image: None
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.46it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.21it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
Done. progress:  73%|█████████████████████████████████████████████▎                | 292/400 [12:45<01:14,  1.46it/s]
C:\Users\derec\miniconda3\envs\film\lib\site-packages\apache_beam\__init__.py:79: UserWarning: This version of Apache Beam has not been sufficiently tested on Python 3.9. You may encounter bugs or missing features.
  warnings.warn(
W0827 18:25:08.952862 19620 environments.py:371] Make sure that locally built Python SDK docker image has Python 3.9 interpreter.
I0827 18:25:08.953861 19620 environments.py:380] Default Python SDK image for environment is apache/beam_python3.9_sdk:2.34.0
I0827 18:25:08.980863 19620 translations.py:678] ==================== <function annotate_downstream_side_inputs at 0x0000026BF5B86AF0> ====================
I0827 18:25:08.981865 19620 translations.py:678] ==================== <function fix_side_input_pcoll_coders at 0x0000026BF5B86C10> ====================
I0827 18:25:08.984863 19620 translations.py:678] ==================== <function pack_combiners at 0x0000026BF5B87160> ====================
I0827 18:25:08.986864 19620 translations.py:678] ==================== <function lift_combiners at 0x0000026BF5B871F0> ====================
I0827 18:25:08.987863 19620 translations.py:678] ==================== <function expand_sdf at 0x0000026BF5B873A0> ====================
I0827 18:25:08.989862 19620 translations.py:678] ==================== <function expand_gbk at 0x0000026BF5B87430> ====================
I0827 18:25:08.990862 19620 translations.py:678] ==================== <function sink_flattens at 0x0000026BF5B87550> ====================
I0827 18:25:08.992862 19620 translations.py:678] ==================== <function greedily_fuse at 0x0000026BF5B875E0> ====================
I0827 18:25:08.994862 19620 translations.py:678] ==================== <function read_to_impulse at 0x0000026BF5B87670> ====================
I0827 18:25:08.999864 19620 translations.py:678] ==================== <function impulse_to_input at 0x0000026BF5B87700> ====================
I0827 18:25:09.000862 19620 translations.py:678] ==================== <function sort_stages at 0x0000026BF5B87940> ====================
I0827 18:25:09.002864 19620 translations.py:678] ==================== <function setup_timer_mapping at 0x0000026BF5B878B0> ====================
I0827 18:25:09.004865 19620 translations.py:678] ==================== <function populate_data_channel_coders at 0x0000026BF5B879D0> ====================
I0827 18:25:09.007863 19620 statecache.py:172] Creating state cache with size 100
I0827 18:25:09.011862 19620 worker_handlers.py:889] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x0000026BF5D73BE0> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0827 18:25:09.013862 19620 fn_runner.py:607] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-3222-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)
Press any key to continue . . .
FILM failed to produce a result.

**Comment by ShmuelRonen** [comment] 2023-08-27 15:47
now let do another thing. I have this script of film:

@echo off

:: Activate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat activate film

:: Execute the Python script for interpolation
python -m eval.interpolator_cli ^
   --pattern "photos" ^
   --model_path pretrained_models\film_net\Style\saved_model ^
   --times_to_interpolate 6 ^
   --output_video

:: Deactivate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat deactivate

pause

**Comment by ShmuelRonen** [comment] 2023-08-27 16:22
The solution I found is to first run the animator at 2 frames per second and then copy the frames to the C:\frame-interpolation\photos folder and run the local script I prepared on them:

@echo off

:: Activate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat activate film

:: Execute the Python script for interpolation
python -m eval.interpolator_cli ^
   --pattern "photos" ^
   --model_path pretrained_models\film_net\Style\saved_model ^
   --times_to_interpolate 6 ^
   --output_video

:: Deactivate the conda environment
call %USERPROFILE%\miniconda3\condabin\conda.bat deactivate

pause


This is the resault:

Before and After


https://github.com/Animator-Anon/animator_extension/assets/80190186/a01c51c2-9424-4438-bb0f-81b91126af64

**Comment by ShmuelRonen** [comment] 2023-08-27 16:30
Animator is a great tool for me and it functions in the SDXL environment without any problems. It deserves further development...

**Comment by ShmuelRonen** [comment] 2023-08-27 16:34
One more little thing. Can it be fixed that it does not allow styles to be activated?

Error: Failed to apply styles to templates: argument of type 'NoneType' is not iterable

**Comment by Animator-Anon** [comment] 2023-08-28 00:10
So the issue is the bat file fails when called by the script?
Can you remove the @echo off so I can see the output from the script?

**Comment by ShmuelRonen** [comment] 2023-08-28 02:46
This is without @ehco

W:\stable-diffusion-webui\extensions\animator_extension>pushd C:\frame-interpolation

C:\frame-interpolation>call C:\Users\derec\miniconda3\condabin\conda.bat activate film
C:\Users\derec\miniconda3\envs\film\lib\site-packages\apache_beam\__init__.py:79: UserWarning: This version of Apache Beam has not been sufficiently tested on Python 3.9. You may encounter bugs or missing features.
  warnings.warn(
W0828 05:42:14.850403  9684 environments.py:371] Make sure that locally built Python SDK docker image has Python 3.9 interpreter.
I0828 05:42:14.852406  9684 environments.py:380] Default Python SDK image for environment is apache/beam_python3.9_sdk:2.34.0
I0828 05:42:14.881404  9684 translations.py:678] ==================== <function annotate_downstream_side_inputs at 0x0000013C2C401B80> ====================
I0828 05:42:14.883407  9684 translations.py:678] ==================== <function fix_side_input_pcoll_coders at 0x0000013C2C401CA0> ====================
I0828 05:42:14.890404  9684 translations.py:678] ==================== <function pack_combiners at 0x0000013C2C4061F0> ====================
I0828 05:42:14.893405  9684 translations.py:678] ==================== <function lift_combiners at 0x0000013C2C406280> ====================
I0828 05:42:14.895404  9684 translations.py:678] ==================== <function expand_sdf at 0x0000013C2C406430> ====================
I0828 05:42:14.896404  9684 translations.py:678] ==================== <function expand_gbk at 0x0000013C2C4064C0> ====================
I0828 05:42:14.901406  9684 translations.py:678] ==================== <function sink_flattens at 0x0000013C2C4065E0> ====================
I0828 05:42:14.903405  9684 translations.py:678] ==================== <function greedily_fuse at 0x0000013C2C406670> ====================
I0828 05:42:14.906404  9684 translations.py:678] ==================== <function read_to_impulse at 0x0000013C2C406700> ====================
I0828 05:42:14.912404  9684 translations.py:678] ==================== <function impulse_to_input at 0x0000013C2C406790> ====================
I0828 05:42:14.914405  9684 translations.py:678] ==================== <function sort_stages at 0x0000013C2C4069D0> ====================
I0828 05:42:14.916405  9684 translations.py:678] ==================== <function setup_timer_mapping at 0x0000013C2C406940> ====================
I0828 05:42:14.924406  9684 translations.py:678] ==================== <function populate_data_channel_coders at 0x0000013C2C406A60> ====================
I0828 05:42:14.927405  9684 statecache.py:172] Creating state cache with size 100
I0828 05:42:14.933406  9684 worker_handlers.py:889] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x0000013C2C8C0670> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0828 05:42:14.935406  9684 fn_runner.py:607] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-3222-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)
FILM failed to produce a result.

**Comment by ShmuelRonen** [comment] 2023-08-28 03:06
It seems that I need to rebuild the film conda env with a python 3.8 installation and not with 3.9 so that it is compatible with the version of apache beam that is installed using the requirements.txt

**Comment by ShmuelRonen** [comment] 2023-08-28 06:39
I rebuild the film conda env with a python 3.8 installation and cheke that it's work with frame interpolation locally. and everything was fine. but when run it from Animator extension i got this:

100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.16it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.16it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.16it/s]
Done. progress: 100%|████████████████████████████████████████████████████████████| 400/400 [3:52:54<00:00,  1.46it/s]

W:\stable-diffusion-webui\extensions\animator_extension>pushd C:\frame-interpolation

C:\frame-interpolation>call C:\Users\derec\miniconda3\condabin\conda.bat activate film

(film) C:\frame-interpolation>python -m eval.interpolator_cli --pattern "outputs/img2img-images\20230828092612" --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate 0
W0828 09:30:47.841597 17420 environments.py:371] Make sure that locally built Python SDK docker image has Python 3.8 interpreter.
I0828 09:30:47.841597 17420 environments.py:380] Default Python SDK image for environment is apache/beam_python3.8_sdk:2.34.0
I0828 09:30:47.861600 17420 translations.py:678] ==================== <function annotate_downstream_side_inputs at 0x000001FFB418B820> ====================
I0828 09:30:47.863598 17420 translations.py:678] ==================== <function fix_side_input_pcoll_coders at 0x000001FFB418B940> ====================
I0828 09:30:47.865597 17420 translations.py:678] ==================== <function pack_combiners at 0x000001FFB418BE50> ====================
I0828 09:30:47.867598 17420 translations.py:678] ==================== <function lift_combiners at 0x000001FFB418BEE0> ====================
I0828 09:30:47.869600 17420 translations.py:678] ==================== <function expand_sdf at 0x000001FFB41EB0D0> ====================
I0828 09:30:47.871598 17420 translations.py:678] ==================== <function expand_gbk at 0x000001FFB41EB160> ====================
I0828 09:30:47.872598 17420 translations.py:678] ==================== <function sink_flattens at 0x000001FFB41EB280> ====================
I0828 09:30:47.875598 17420 translations.py:678] ==================== <function greedily_fuse at 0x000001FFB41EB310> ====================
I0828 09:30:47.879602 17420 translations.py:678] ==================== <function read_to_impulse at 0x000001FFB41EB3A0> ====================
I0828 09:30:47.881598 17420 translations.py:678] ==================== <function impulse_to_input at 0x000001FFB41EB430> ====================
I0828 09:30:47.884597 17420 translations.py:678] ==================== <function sort_stages at 0x000001FFB41EB670> ====================
I0828 09:30:47.892598 17420 translations.py:678] ==================== <function setup_timer_mapping at 0x000001FFB41EB5E0> ====================
I0828 09:30:47.894597 17420 translations.py:678] ==================== <function populate_data_channel_coders at 0x000001FFB41EB700> ====================
I0828 09:30:47.896597 17420 statecache.py:172] Creating state cache with size 100
I0828 09:30:47.899597 17420 worker_handlers.py:889] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x000001FFB45F6070> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0828 09:30:47.900599 17420 fn_runner.py:607] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-3222-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)

(film) C:\frame-interpolation>call C:\Users\derec\miniconda3\condabin\conda.bat deactivate
FILM failed to produce a result.

**Comment by Animator-Anon** [comment] 2023-08-29 00:50
I have no idea what is going on or why it is not working in your environment. It looks like you did everything right. Suffice to say, it appears as though FILM does not run successfully when called by my script.
All my script is doing is calling the bat file with two command line arguments, the folder containing the frames you have just rendered, and the number of iterations.
When the subprocess returns, it checks for the interpolated_frames subfolder, and if it exists, replaces the original frames with the ones from this folder.
If the interpolated_frames subfolder does not exist, it fails saying FILM didn't produce an output.
It should create a makefilm.bat file with this command line in it in the output folder. Can you manually run this?

**Comment by ShmuelRonen** [comment] 2023-08-29 03:00
From your words the mystery became clear. I didn't set the new output folder... now everything works. Thanks

**Comment by Animator-Anon** [comment] 2023-08-30 03:33
Great, post a new video. Your generations seem quite interesting.

**Comment by ShmuelRonen** [comment] 2023-08-30 10:51
> Great, post a new video. Your generations seem quite interesting.

Ok. So here is a work I did when the base was a video created in Animator with Film activated.
The first video is the raw product and the second is what I made from it.

https://github.com/Animator-Anon/animator_extension/assets/80190186/d8ae6e77-7b62-4df4-baa9-1483b5b73021

https://fb.watch/mKSaYl1Tfv/

**Comment by mikecastrodemaria** [comment] 2023-08-30 18:20
Heoolo, same problem on macos : 

FILM could not be found in this folder: C:/AI/frame_interpolation
*** Error completing request

FILM interpolation is not checked in the settings.

mac / unix users note use .bat file, maybe .sh as SD, but .bat is only PC 

Have you a mac/unix install process ? Before the anmator was working without this on macos.

**Comment by Animator-Anon** [comment] 2023-08-31 02:49
I have no advice on installing FILM on macos. It sounds like it couldn't find an appropriate dependency, tensorflow==2.6.2. You need to figure this out.

As for the error, you wrote  ' 0 .3' at the start of a keyframe. There is a space between the 0 and the .3 that shouldn't be there, python doesn't understand what you wrote and can't convert it to a number.

**Comment by mikecastrodemaria** [comment] 2023-08-31 12:57
Ok problem solved, many thanks the first error war related to missing FILM, second was due to settings , third was related to  0 .3.

**Closed** 2023-08-31 14:03 UTC
